apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels: # labels to select/identify the deployment
        app: nginx
    spec:     # pod spec                  
      containers: 
      - name: nginx
        image: nginx:1.16 # image we pushed
        ports:
        - containerPort: 8080